name: "Pocket weekly reading list"
on:
  workflow_dispatch:
  schedule:
    - cron: "11 8 * * SUN"

jobs:
  request:
    name: API Request to Pocket
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Calculate Unix timestamp from a week ago
        id: since
        run: echo "::set-output name=SINCE::$(date --date='1 week ago' +%s)"
      - name: Web Request Action
        id: archive
        uses: Satak/webrequest-action@v1.2.3
        env:
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_TOKEN: ${{ secrets.POCKET_TOKEN }}
          PAR_state: "unread"
          PAR_sort: "oldest"
          PAR_since: ${{ steps.since.outputs.SINCE }}
        with:
          url: https://getpocket.com/v3/get
          method: POST
          payload: '{"consumer_key": "${{ env.POCKET_CONSUMER_KEY }}", "access_token": "${{ env.POCKET_TOKEN }}", "state": "${{ env.PAR_state }}", "sort": "${{ env.PAR_sort }}", "since": "${{ env.PAR_since }}"}'
      - name: Create weekly file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: '$(date +"%Y-%M-%D").json'
          json: '${{ steps.archive.outputs.output }}'
      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Automated weekly archive
